-- Seed งานกลาง MA (state.events) ที่ migration ไม่ได้ย้ายมา — รันใน Supabase SQL Editor
-- แหล่งข้อมูล: แท็บ _state ของ sheet (version 376) · สร้าง 2026-09-03
begin;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (3,'2026-08-25','all',{all},'Symposium: Mastering Facial Filler and Skin-Structure Bio-Regenerator Injection: Anatomy, Safe Techniques and Complication Management','',null,{},'{"src": "EV", "id": "EV-3", "date": "2026-08-25", "slot": "all", "type": "Symposium", "title": "Symposium: Mastering Facial Filler and Skin-Structure Bio-Regenerator Injection: Anatomy, Safe Techniques and Complication Management", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (6,'2026-08-31','all',{all},'Monthly Training and Commercial Updates','',null,{},'{"src": "EV", "id": "EV-6", "date": "2026-08-31", "slot": "all", "type": "MA Central Event", "title": "Monthly Training and Commercial Updates", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (7,'2026-09-01','all',{all},'Commercial Updates and Discussion & 💉Vaccine Flu','',null,{},'{"src": "EV", "id": "EV-7", "date": "2026-09-01", "slot": "all", "type": "MA Central Event", "title": "Commercial Updates and Discussion & 💉Vaccine Flu", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (8,'2026-09-02','all',{all},'📚 OTOS : Belotero Intense Hands on','',null,{},'{"src": "EV", "id": "EV-8", "date": "2026-09-02", "slot": "all", "type": "MA Central Event", "title": "📚 OTOS : Belotero Intense Hands on", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (10,'2026-09-15','all',{"narakamon","kanwara","pariyachat","pitchaporn","belle","parichat"},'Radiesse Skin-Structure Symposium (HCP, Marketing and PC Training)','',null,{},'{"src": "EV", "id": "EV-10", "date": "2026-09-15", "slot": "all", "type": "Symposium", "title": "Radiesse Skin-Structure Symposium (HCP, Marketing and PC Training)", "cts": ["narakamon", "kanwara", "pariyachat", "pitchaporn", "belle", "parichat"]}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (11,'2026-09-14','am',{all},'CTS Monthly Meeting','',null,{},'{"src": "EV", "id": "EV-11", "date": "2026-09-14", "slot": "am", "type": "MA Central Event", "title": "CTS Monthly Meeting", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (12,'2026-09-29','all',{all},'Monthly Training and Commercial Updates','',null,{},'{"src": "EV", "id": "EV-12", "date": "2026-09-29", "slot": "all", "type": "MA Central Event", "title": "Monthly Training and Commercial Updates", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (13,'2026-09-30','all',{all},'Quarterly Town Hall, Commercial Updates and Discussion','',null,{},'{"src": "EV", "id": "EV-13", "date": "2026-09-30", "slot": "all", "type": "Workshop", "title": "Quarterly Town Hall, Commercial Updates and Discussion", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (14,'2026-10-01','all',{all},'Team building @Khaoyai','',null,{},'{"src": "EV", "id": "EV-14", "date": "2026-10-01", "slot": "all", "type": "MA Central Event", "title": "Team building @Khaoyai", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (15,'2026-10-02','all',{all},'Team building @Khaoyai','',null,{},'{"src": "EV", "id": "EV-15", "date": "2026-10-02", "slot": "all", "type": "MA Central Event", "title": "Team building @Khaoyai", "cts": "all"}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
insert into public.events (id,date,slot,cts,title,detail,product,topics,client) values (16,'2026-09-25','all',{"koollanut","kanwara","pariyachat","pitchaporn","belle","parichat","witchukorn"},'Ultherapy PRIME Center of Excellence (Face & Body)','',null,{},'{"src": "EV", "id": "EV-16", "date": "2026-09-25", "slot": "all", "type": "Workshop", "title": "Ultherapy PRIME Center of Excellence (Face & Body)", "cts": ["koollanut", "kanwara", "pariyachat", "pitchaporn", "belle", "parichat", "witchukorn"]}'::jsonb) on conflict (id) do update set date=excluded.date,slot=excluded.slot,cts=excluded.cts,title=excluded.title,detail=excluded.detail,product=excluded.product,topics=excluded.topics,client=excluded.client;
commit;